### ISSUE TITLE
run clamav againt file not running

### ISSUE THREAD

**Issue by azfayel** [maliceio/malice-av#1]
Hi,
I follow the instructions given through the command 
ocker restart clamav > /dev/null && docker exec clamav scan --table EICAR
and i get the output 
Error response from daemon: Container 6ca35ad7f7c7f36a56f3ebc3cb5c046402f9bf0043e0315324a8231d560b3b38 is not running: Exited (0) Less than a second ago
but the command "docker run --rm malice/clamav EICAR" outputs
 {"clamav":{"infected":true,"result":"Eicar-Test-Signature","engine":"0.99","known":"4276723","updated":"20160228"}}

I also tried docker run --rm -v /evidences/eicar/:/malware:ro malice/clamav
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
docker: Error response from daemon: Cannot start container 925a92e985810f18fa22788fc1df114ca7381da110e5f76c6411eeded7658247: [9] System error: not a directory.

It seems that de clamav container is not running or cannot bind the volume in the host ?

Thks in advance for your enlightment.

**Comment by blacktop** [comment]
@azfayel  thank you for bringing this to my attention.  I realize that they way I was trying to handle AV updates was silly.  I think this is a much better way:

To update the AV run the following:
```bash
$ docker run --name=clamav malice/clamav update
```
Then to use the updated ClamAV container:
```bash
$ docker commit clamav malice/clamav
$ docker rm clamav # clean up updated container
$ docker run --rm malice/clamav EICAR
```

Thank you.
