### ISSUE TITLE
submit a file to analysis

### ISSUE THREAD

**Issue by azfayel** [maliceio/malice-av#2]
I understand that i can user run or exec  docker command but the args are a little bit confused.Also i used -v to bin a host host volume and supplied the file but something went wrong.
Can you give us the right path to scan a file ?

regards,

richard

**Comment by blacktop** [comment]
here is an example of how to scan some malware on OSX using a docker-machine:

```bash
docker run -v $(pwd):/malware malice/clamav -t befb88b89c2eb401900a68e9f5b78764203f2b48264fcc3f7121bf04a57fd408
```
Output
#### ClamAV
| Infected | Result               | Engine | Updated  |
| -------- | -------------------- | ------ | -------- |
| true     | Win.Trojan.Backspace | 0.99   | 20160229 |

**Comment by blacktop** [comment]
Does this not work for you?  What OS/docker version are you using?

**Comment by azfayel** [comment]
Hi,
I used this command and it works! Thk you for your assistance.

**Comment by blacktop** [comment]
you are very welcome.
