### ISSUE TITLE
add new anti virus

### ISSUE THREAD

**Issue by jjjan** [maliceio/malice-av#3]
please add Kaspersky  anti virus and make some section to register anti virus

**Comment by blacktop** [comment]
I am starting it here: https://github.com/malice-plugins/kaspersky

I can't figure out how to get a trial license.key though?  They give you activation codes that I don't understand how to turn into keys?

Do you know how I can get a trial key?

**Comment by jjjan** [comment]
give me the version of product you need.

**Comment by blacktop** [comment]
https://products.s.kaspersky-labs.com/multilanguage/file_servers/kavlinuxserver8.0/kav4fs_8.0.4-312_i386.deb

**Comment by jjjan** [comment]
ok give me the name.

**Comment by blacktop** [comment]
Kaspersky
Security for File Server for Linux

**Comment by blacktop** [comment]
Apparently you can't get a trial license for Corp products?

**Comment by blacktop** [comment]
@jjjan were you able to find a trial key for that product?
