### ISSUE TITLE
File submission?

### ISSUE THREAD

**Issue by gabegarz** [maliceio/malice-av#4]
I want to use the avast av as an engine so that I can submit files to it either one at a time or a directory of files.  How would I do that with this docker?

**Comment by blacktop** [comment]
Have you looked at https://github.com/maliceio/malice yet?

**Comment by blacktop** [comment]
Also Avast changed the way it's installer works.  I have contacted their customer support several times to see if I could get it working again and they can't seem to help me :'(

I am not sure I will be able to get it working again.  You can see what AVs are working in the main README

**Comment by gabegarz** [comment]
Should I look at the scan.go file for this?  Thanks again great product!

**Comment by blacktop** [comment]
I got avast to work again! 😎 - https://github.com/maliceio/malice-avast and you can create a web service and submit files to it as can be seen here - https://github.com/maliceio/malice-avast/blob/master/docs/web.md
