### ISSUE TITLE
The avg image does not build

### ISSUE THREAD

**Issue by unclev** [maliceio/malice-av#5]
When it builds it returns avgscan compilation error.
Steps to reproduce:
```bash
git clone https://github.com/maliceio/malice-av.git src
cd src/avg
rm build.* ; docker build -t malice/avg . | tee build.log
```
Skipping the output of `docker build -t malice/avg .` The output of `tail -n 20 build.log` below.
```
AVG command line avgcfgctl
Copyright (c) 2013 AVG Technologies CZ

Setting configuration item Default.setup.daemonize to value false.
Install Go...
Building avscan Go binary...
go version go1.7.1 linux/amd64
# github.com/maliceio/malice-avg
./scan.go:109: cannot use "/usr/bin/avgscan" (type string) as type context.Context in argument to utils.RunCommand:
        string does not implement context.Context (missing Deadline method)
./scan.go:109: multiple-value utils.RunCommand() in single-value context
./scan.go:148: not enough arguments in call to utils.RunCommand
./scan.go:255: cannot use "/usr/bin/avgscan" (type string) as type context.Context in argument to utils.RunCommand:
        string does not implement context.Context (missing Deadline method)
./scan.go:255: multiple-value utils.RunCommand() in single-value context
./scan.go:258: cannot use "/usr/bin/avgscan" (type string) as type context.Context in argument to utils.RunCommand:
        string does not implement context.Context (missing Deadline method)
./scan.go:258: multiple-value utils.RunCommand() in single-value context
./scan.go:267: not enough arguments in call to elasticsearch.InitElasticSearch
```

**Comment by blacktop** [comment]
So it requires go 1.7.3+  It looks like you don't have the proper **context** lib which was introduced in golang 1.7.2 or 1.7.3 I think?

**Comment by blacktop** [comment]
Also I started to break the malice AVs into their own repos so that code might be old(er) - here is the newer stuff - https://github.com/maliceio/malice-avg

**Comment by unclev** [comment]
the cited text was just from this docker build output, and yes, the Dockerfile specifies GO_VERSION 1.7.1. Thank you for pointing on the newer repo. The docker's trusted build refers to the older repo though. From the new repo it builds (and still does not work  in my case (see my comment to the docker [trusted build](https://hub.docker.com/r/malice/avg/)), - but this is different issue).

**Comment by blacktop** [comment]
Thank you for letting me know, I think I might need to give malice some love and attention this weekend :wink:

**Comment by blacktop** [comment]
@unclev I have fixed the issue now.  I also added a beta version of a micro-service mode for the malice/avg scanner here - https://github.com/maliceio/malice-avg#create-a-avg-scan-micro-service-new-construction
