### ISSUE TITLE
vbacl-linux-3.12.26.4.tar.gz archive for VirusBlokAda is corrupt and link is broken

### ISSUE THREAD

**Issue by morrowd** [maliceio/malice-av#6]
The vbacl-linux-3.12.26.4.tar.gz archive for VirusBlokAda is corrupt. Additionally, the link for download http://anti-virus.by/pub/vbacl-linux-3.12.26.4.tar.gz is broken. Is it possible to upload a working vbacl-linux-3.12.26.4.tar.gz archive or possibly a live link for download. Thanks.

With gzip-

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

With 7z.exe-

Data error in 'vbacl-linux-3.12.26.4.tar'. File is broken

**Comment by blacktop** [comment]
Not all the AV folders work, they ones that do are mentioned in the README and they have links to their up-to-date maintained individual repos.  

The folders that are there that aren't mentioned in the README are either works-in-progress OR things I wanted to try to 'docker-ize', but weren't sure if it was possible or not.

I would love any help with good links to AV installers and/or POCs on working install scripts for AVs I have?
