### ISSUE TITLE
Possible Avira License Solution

### ISSUE THREAD

**Issue by morrowd** [maliceio/malice-av#7]
If you reach out to Avira Labs they may grant you a free license for research purposes. I have been able to do this in the past along with an agreement if you encounter malware Avira does not detect and has not already been submitted to VirusTotal, then you upload it to their labs. If you have questions I can provide contact info offline or via private message.

**Comment by blacktop** [comment]
The original reason I EOLd Avira was because they changed (or docker) changed something and I could no longer get it to install.  I contacted Avira's customer support several times and they weren't able to help or didn't care to.  I haven't tried in a while so maybe they fixed it since then?

**Comment by blacktop** [comment]
Hmmm I was looking at the readme and it has been a long time since I thought about Avira, maybe I did get it to work and the reason it was failing was because they stopped supporting free licenses?

**Comment by blacktop** [comment]
A good was to contact me is via keybase.io chat?

**Comment by kvozon** [comment]
I just installed on Ubuntu 17.04 Avira Command Line Scanner ScanCL from their official site, updated it with Fusebundle Generator and used a key from Avira Free edition (installed on windows). Everything works fine, maybe you can create a docker with this solution?

**Comment by blacktop** [comment]
I will try again soon, but I do remember it works differently in docker than say in a normal ubuntu VM, because docker blacklists certain 'dangerous' syscalls etc

**Comment by blacktop** [comment]
I have reached out to Avira asking for a research key.  I will also try your hack @kvozon as it sounds like a good idea.

**Comment by blacktop** [comment]
@kvozon can you share an example bash script on how you got it to work?  it seems like scancl needs other libraries?

**Comment by blacktop** [comment]
update I think I figured out that you run fusebundle and then unzip to the scancl dir, but the hbdev.key I got from a free OSX install didn't work.  scanCL said `ERROR: [No license found] Initialization` does it need to be in a certain dir or have a certain name?

**Comment by blacktop** [comment]
https://github.com/malice-plugins/avira
